export interface OceanWord {
  en: string
  zh: string
}

export const OCEAN_WORDS: OceanWord[] = [
  { en: 'tide', zh: '潮汐' },
  { en: 'current', zh: '洋流' },
  { en: 'coral', zh: '珊瑚' },
  { en: 'abyss', zh: '深淵' },
  { en: 'horizon', zh: '海平線' },
  { en: 'lagoon', zh: '潟湖' },
  { en: 'drift', zh: '漂流' },
  { en: 'serene', zh: '寧靜' },
  { en: 'azure', zh: '蔚藍' },
  { en: 'whisper', zh: '低語' },
  { en: 'stillness', zh: '靜謐' },
  { en: 'breathe', zh: '呼吸' },
  { en: 'float', zh: '漂浮' },
  { en: 'glow', zh: '微光' },
  { en: 'depth', zh: '深度' },
  { en: 'wave', zh: '波浪' },
  { en: 'calm', zh: '平靜' },
  { en: 'shimmer', zh: '閃爍' },
  { en: 'dawn', zh: '黎明' },
  { en: 'starseed', zh: '星靈種子' },
  { en: 'crystal', zh: '水晶' },
  { en: 'harbor', zh: '港灣' },
  { en: 'kelp', zh: '海帶' },
  { en: 'foam', zh: '泡沫' },
  { en: 'driftwood', zh: '浮木' },
  { en: 'tranquil', zh: '恬靜' },
  { en: 'ripple', zh: '漣漪' },
  { en: 'moonlight', zh: '月光' },
  { en: 'resonance', zh: '共振' },
  { en: 'harmony', zh: '和諧' },
  { en: 'gentle', zh: '溫柔' },
  { en: 'ebb', zh: '退潮' },
  { en: 'swell', zh: '湧浪' },
  { en: 'saltwater', zh: '鹹水' },
  { en: 'reef', zh: '礁岩' },
  { en: 'plankton', zh: '浮游生物' },
  { en: 'undertow', zh: '暗流' },
  { en: 'pearl', zh: '珍珠' },
  { en: 'anchor', zh: '錨' },
  { en: 'sanctuary', zh: '聖所' },
  { en: 'refuge', zh: '庇護所' },
  { en: 'weightless', zh: '失重' },
  { en: 'buoyant', zh: '浮力' },
  { en: 'translucent', zh: '半透明' },
  { en: 'luminous', zh: '發光的' },
  { en: 'cove', zh: '小海灣' },
]
